[phases.setup]
nixPkgs = ["nodejs_20", "python311"]

[phases.install]
cmds = [
    "npm ci --production",
    "pip install --user youtube-transcript-api"
]

[start]
cmd = "node index.js"

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"
NIXPACKS_NODE_VERSION = "20"